### ISSUE TITLE
scalar.rs

### ISSUE THREAD

**Issue by dot-asm** [dignifiedquire/blstrs#10]
I'd like to make a case for deep makeover of this [module]. I feel that this is serious mischaracterization to mix together "scalar" and "fr" field operations. Scalars are something you multiply points by, "fr"-s are something you operate on in their own [capacity]. They have different internal representations and should be treated as independent types. Most notably, I'm considering switching for bytes in scalars.

It's not exactly my business, but I'm opposed to the idea of implementing methods just for the sake of "completeness." For example there is no point implementing fp12 addition or subtraction. Is it actually so that caller of the module is dependent on them, or are they used only in internal tests? If latter, then what's the actual point of implementing them? Same applies to sqrt and inverse. So far assessment is that need for sqrt would disappear if #6 is resolved as suggested. At least for fp and fp2. Is it correct or what am I missing? As for fr, is it's actually so that sqrt and inverse are required for something? If so, I'm ready to add them to blst...

**Comment by dignifiedquire** [comment]
> I feel that this is serious mischaracterization to mix together "scalar" and "fr" field operations

There is a different terminology used in the bls12 implementation here: https://github.com/zkcrypto/bls12_381, where `Scalar` is what is called in other places `Fr`, because it is the `Scalar` Field of `F_q`. So I would like to keep this naming convention in here.

**Comment by dignifiedquire** [comment]
- `Sqrt` is mainly used in this repo for some fallback impls
- `inverse` is used in `bellman`

But for both, I do need the implementations, as the current trait systems does require to have them, and I would rather have a rust fallback than a panic about it not being implemented, if they don't get added to `blst`

**Comment by dot-asm** [comment]
> There is a different terminology used in the bls12 implementation here: https://github.com/zkcrypto/bls12_381, where Scalar is what is called in other places Fr, because it is the Scalar Field of F_q. So I would like to keep this naming convention in here.

Well, mathematically they are interchangeable in sense that operations on either are modulo same modulus. But the concern is non-mathematical. As already said, when it comes to computations blst_scalar and blst_fr are effectively independent types. And now you're throwing in ScalarRepr, which is 3rd effectively independent type... Just in case, I'm not pretending to have figured it **all** out. You are naturally free to refer to blst_fr as Scalar, but it's arguably taking some mental gymnastics to hold it mind. Well, you might as well counter-argue that it's just me:-)

Either way. ScalarRepr deserves same treatment as other \*Repr. In sense that it should be declared as [u64; 4]. This means that it would be appropriate to have blst_fr_from_uint64 and uint64_to_fr... Added. I've also added fr_from_scalar and scalar_from_fr...

**Comment by dignifiedquire** [comment]
reworked scalar repr in e90bef1 using the new API you added, thanks

**Comment by dignifiedquire** [comment]
> Just in case, I'm not pretending to have figured it **all** out.

Thanks, I neither have things figured, so much is for sure, just trying to follow in the footsteps of other great folks.

**Comment by dot-asm** [comment]
> Sqrt is mainly used in this repo for some fallback impls

What prevents you from always returning None, if it's only a question of "trait completeness"?

> inverse is used in bellman

It makes sense to implement it then. Does it have to be constant-time? Because if not, then Euclidean algorithm would perform better...

**Comment by dignifiedquire** [comment]
no need for constant time for the snarks

**Comment by dot-asm** [comment]
`blst_fr_eucl_inverse` is added.

**Comment by dignifiedquire** [comment]
should all be resolved in the latest code
