### ISSUE TITLE
Pairing Issue

### ISSUE THREAD

**Issue by dignifiedquire** [dignifiedquire/blstrs#11]
Currently these https://github.com/dignifiedquire/blstrs/blob/master/src/tests/engine.rs#L35-L49 tests are failing, while all other pairing checks are passing, this might be an issue in blst itself. 

@dot-asm could you take a look if this might be an issue in blst for these special cases?

**Comment by dot-asm** [comment]
There is ongoing dispute on how to treat infinity points. Trouble is that infinite individual signatures are devoid of cryptographic properties and formally speaking outcome of verification should be considered undefined. Kind of like comparing floating point NaNs. Either way, once dispute is settled (at bls-signature draft level), it will be resolved accordingly.

**Comment by dignifiedquire** [comment]
Thanks for the info, I have hardcoded the behaviour matching `pairing` for now in this library, to keep the consistency there, independently of the bls-signature decision.
