### ISSUE TITLE
impl Neg for Fp

### ISSUE THREAD

**Issue by dot-asm** [dignifiedquire/blstrs#2]
This is rather a wonder. Why is following needed?

https://github.com/dignifiedquire/blstrs/blob/df8c49dbe3f1621ff10c393691cbd59358c29bb2/src/fp.rs#L556-L563

I mean there is life-time-d version above...

**Comment by dignifiedquire** [comment]
it is a convenience implementation, so you can write `let b = -a`, instead of `let b = -&a`, in the case that `a` is an `Fp`.
