### ISSUE TITLE
impl fff::Field for Fp

### ISSUE THREAD

**Issue by dot-asm** [dignifiedquire/blstrs#3]
I don't follow this

https://github.com/dignifiedquire/blstrs/blob/df8c49dbe3f1621ff10c393691cbd59358c29bb2/src/fp.rs#L600-L612

`raw` is 6 limbs, 4 are set, 4th is masked... So if FpRepr(raw) < MODULUS is always true... And it would hold true even without masking...

Formally speaking you don't need this loop at all, because conversion to blst_fp does implicit modulo reduction. Yes, you can pass full-width 384-bit input to conversion subroutine and it will be reduced modulo field prime, i.e. you'll get `random % prime` for free. Which is obviously as good as checking for < MODULUS. (Provided that one would fill 6 limbs and mask 6th.)

**Comment by dignifiedquire** [comment]
Thanks, copy & paste is hard..
