### ISSUE TITLE
Fp::from_bytes_le

### ISSUE THREAD

**Issue by dot-asm** [dignifiedquire/blstrs#4]
https://github.com/dignifiedquire/blstrs/blob/df8c49dbe3f1621ff10c393691cbd59358c29bb2/src/fp.rs#L808-L815

Doesn't straight `bytes.as_ptr()` work? And I don't follow raw.try_into().ok().

Same applies to from_bytes_be... And to_bytes, modulo out.as_mut_ptr()...

**Comment by dignifiedquire** [comment]
yes `as_ptr()` works fine for arrays, I am not sure how I didn't get this the first time around
