### ISSUE TITLE
impl Ord for Fp2

### ISSUE THREAD

**Issue by dot-asm** [dignifiedquire/blstrs#5]
https://github.com/dignifiedquire/blstrs/blob/df8c49dbe3f1621ff10c393691cbd59358c29bb2/src/fp2.rs#L59-L69

I don't think this is "lexicographical" comparison. Or what am I missing? Otherwise I can arrange export of sgn0_fp2...

**Comment by dot-asm** [comment]
I've misread, sorry about confusion.

However, if this comparison is used in actual production code, then it might make sense to implement it in blts. I can imagine it can be useful when arranging public keys, though I can also imagine that it might make more sense to keep serialized copy and use that for comparison. On the other hand serialized key can be compressed and if y coordinate is factored in, it wouldn't do. Or it, compressed key, might be exactly right, since keys can be arranged by x alone whith y's sign...

**Comment by dignifiedquire** [comment]
It is useful to have an ordering defined, but I don't think it is actively used in production code atm, so I think it is fine to be left as is for now.
