### ISSUE TITLE
random in g1.rs

### ISSUE THREAD

**Issue by dot-asm** [dignifiedquire/blstrs#6]
Why not replace this

https://github.com/dignifiedquire/blstrs/blob/df8c49dbe3f1621ff10c393691cbd59358c29bb2/src/g1.rs#L569-L582

with call to `blst_encode_to_g1` with random `msg` instead? No loops, predictable time, reliable output... And you can omit `get_point_from_x` and `scale_by_cofactor`.

Same applies to g2.

**Comment by dignifiedquire** [comment]
thanks, this is nicer indeed
