### ISSUE TITLE
is_zero is g1.c

### ISSUE THREAD

**Issue by dot-asm** [dignifiedquire/blstrs#7]
https://github.com/dignifiedquire/blstrs/blob/df8c49dbe3f1621ff10c393691cbd59358c29bb2/src/g1.rs#L593-L596

I make no promises about x and y being zero along with z.

**Comment by dignifiedquire** [comment]
Then what promises can I rely on for checking for the point at infinity?

**Comment by dot-asm** [comment]
I've added `blst_*_is_inf` functions to blst.

**Comment by dignifiedquire** [comment]
thank you

**Comment by dignifiedquire** [comment]
Fixed in 16caac5

**Comment by dot-asm** [comment]
While you are at it, switch to `blst_*_generator()`... I'm considering dropping data constants from bindings...
