### ISSUE TITLE
double in g1.rs

### ISSUE THREAD

**Issue by dot-asm** [dignifiedquire/blstrs#8]
https://github.com/dignifiedquire/blstrs/blob/df8c49dbe3f1621ff10c393691cbd59358c29bb2/src/g1.rs#L615-L621

blst_p1_double. It's faster.

On vaguely related note. Lucky you since double type is called f64 in Rust :-)

**Comment by dignifiedquire** [comment]
> Lucky you since double type is called f64 in Rust :-)

I thank the rust gods every day for it :D
