### ISSUE TITLE
Should Fp6 be part of the public API?

### ISSUE THREAD

**Issue by dot-asm** [dignifiedquire/blstrs#9]
What prevents you from omitting fp6.rs?

**Comment by dignifiedquire** [comment]
Good question, I mostly added it to match the previous implementation as close as possible, but now that I am looking at the usage, nothing seems to ever use Fp6 outside of the internals.

**Comment by dot-asm** [comment]
> nothing seems to ever use Fp6 outside of the internals

Right. The fp6 is just **a** detail of fp12 implementation. And actually so are fp and fp2. It's just that fp and fp2 are used even in point arithmetic...

**Comment by dot-asm** [comment]
> The fp6 is just a detail of fp12 implementation. And actually so are fp and fp2. It's just that fp and fp2 are used even in point arithmetic...

Meaning that if point interface is sufficient for application purposes (or can be complemented to be sufficient), one can as well omit fp and fp2.

**Comment by dignifiedquire** [comment]
I will leave it for the moment, might revisit later.
